<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;
use App\Models\Service;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            [
                'title_fr' => 'Ravalement de facade - Immeuble residentiel',
                'title_nl' => 'Gevelrenovatie - Residentieel gebouw',
                'description_fr' => 'Renovation complete d\'une facade d\'immeuble de 4 etages avec peinture et finition professionnelle.',
                'description_nl' => 'Volledige renovatie van een gevel van een gebouw van 4 verdiepingen met professionele schildering en afwerking.',
                'image_before' => '/images/projects/project-01-before.jpg',
                'image_after' => '/images/projects/project-01-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 1,
            ],
            [
                'title_fr' => 'Nettoyage de facade - Maison de ville',
                'title_nl' => 'Gevelreiniging - Stadswoning',
                'description_fr' => 'Nettoyage en profondeur d\'une facade en brique avec retrait de graffitis et salissures.',
                'description_nl' => 'Dieptereiniging van een bakstenen gevel met verwijdering van graffiti en vuil.',
                'image_before' => '/images/projects/project-02-before.jpg',
                'image_after' => '/images/projects/project-02-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 2,
            ],
            [
                'title_fr' => 'Hydrogommage - Immeuble commercial',
                'title_nl' => 'Hydrogommage - Commercieel gebouw',
                'description_fr' => 'Nettoyage par hydrogommage d\'une facade d\'immeuble commercial en brique jaune.',
                'description_nl' => 'Reiniging door hydrogommage van een commercieel gebouw met gele bakstenen gevel.',
                'image_before' => '/images/projects/project-03-before.jpg',
                'image_after' => '/images/projects/project-03-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 3,
            ],
            [
                'title_fr' => 'Nettoyage et peinture - Facade en pierre',
                'title_nl' => 'Reiniging en schilderwerk - Stenen gevel',
                'description_fr' => 'Nettoyage anti-graffiti et peinture de facade d\'un immeuble en pierre avec porte et garage.',
                'description_nl' => 'Anti-graffiti reiniging en gevelschildering van een stenen gebouw met deur en garage.',
                'image_before' => '/images/projects/project-04-before.jpg',
                'image_after' => '/images/projects/project-04-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 4,
            ],
            [
                'title_fr' => 'Nettoyage de facade - Maison en brique',
                'title_nl' => 'Gevelreiniging - Bakstenen woning',
                'description_fr' => 'Nettoyage complet d\'une facade en brique avec bow-window et rejointoiement.',
                'description_nl' => 'Volledige reiniging van een bakstenen gevel met erker en hervoegen.',
                'image_before' => '/images/projects/project-05-before.jpg',
                'image_after' => '/images/projects/project-05-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 5,
            ],
            [
                'title_fr' => 'Rejointoiement - Maison residentielle',
                'title_nl' => 'Hervoegen - Residentieel woning',
                'description_fr' => 'Rejointoiement complet et nettoyage d\'une facade de maison residentielle en brique.',
                'description_nl' => 'Volledig hervoegen en reiniging van een bakstenen gevel van een residentieel woning.',
                'image_before' => '/images/projects/project-06-before.jpg',
                'image_after' => '/images/projects/project-06-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 6,
            ],
            [
                'title_fr' => 'Hydrofugation - Villa moderne',
                'title_nl' => 'Hydrofugering - Moderne villa',
                'description_fr' => 'Traitement hydrofuge complet d\'une villa moderne avec grandes baies vitrees.',
                'description_nl' => 'Volledige waterafstotende behandeling van een moderne villa met grote raampartijen.',
                'image_before' => '/images/projects/project-07-before.jpg',
                'image_after' => '/images/projects/project-07-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 7,
            ],
            [
                'title_fr' => 'Nettoyage de terrasse - Paves',
                'title_nl' => 'Terrasreiniging - Klinkers',
                'description_fr' => 'Nettoyage haute pression d\'une allee en paves avec traitement anti-mousse.',
                'description_nl' => 'Hogedrukreiniging van een klinkerpad met anti-mosbehandeling.',
                'image_before' => '/images/projects/project-08-before.jpg',
                'image_after' => '/images/projects/project-08-after.jpg',
                'is_featured' => false,
                'is_published' => true,
                'order' => 8,
            ],
            [
                'title_fr' => 'Nettoyage de facade - Immeuble a appartements',
                'title_nl' => 'Gevelreiniging - Appartementsgebouw',
                'description_fr' => 'Nettoyage complet d\'un immeuble a appartements de 6 etages avec balcons.',
                'description_nl' => 'Volledige reiniging van een appartementsgebouw van 6 verdiepingen met balkons.',
                'image_before' => '/images/projects/project-09-before.jpg',
                'image_after' => '/images/projects/project-09-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 9,
            ],
            [
                'title_fr' => 'Peinture de facade - Maison mitoyenne',
                'title_nl' => 'Gevelschilderwerk - Rijwoning',
                'description_fr' => 'Peinture complete et renovation d\'une facade de maison mitoyenne avec nouveaux chassis.',
                'description_nl' => 'Volledige schildering en renovatie van een rijwoninggevel met nieuwe raamkozijnen.',
                'image_before' => '/images/projects/project-10-before.jpg',
                'image_after' => '/images/projects/project-10-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 10,
            ],
            [
                'title_fr' => 'Nettoyage de facade - Maison de maitre',
                'title_nl' => 'Gevelreiniging - Herenhuis',
                'description_fr' => 'Nettoyage par hydrogommage d\'une facade en pierre de taille d\'une maison de maitre.',
                'description_nl' => 'Reiniging door hydrogommage van een natuurstenen gevel van een herenhuis.',
                'image_before' => '/images/projects/project-11-before.jpg',
                'image_after' => '/images/projects/project-11-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 11,
            ],
            [
                'title_fr' => 'Rejointoiement - Villa en brique',
                'title_nl' => 'Hervoegen - Bakstenen villa',
                'description_fr' => 'Rejointoiement et nettoyage de facade d\'une villa en brique rouge avec veranda.',
                'description_nl' => 'Hervoegen en gevelreiniging van een villa in rode baksteen met veranda.',
                'image_before' => '/images/projects/project-12-before.jpg',
                'image_after' => '/images/projects/project-12-after.jpg',
                'is_featured' => false,
                'is_published' => true,
                'order' => 12,
            ],
            [
                'title_fr' => 'Renovation complete - Immeuble commercial',
                'title_nl' => 'Volledige renovatie - Commercieel gebouw',
                'description_fr' => 'Renovation complete d\'une facade d\'immeuble commercial avec nettoyage, rejointoiement et peinture.',
                'description_nl' => 'Volledige renovatie van een commercieel gebouw met reiniging, hervoegen en schilderwerk.',
                'image_before' => '/images/projects/project-13-before.jpg',
                'image_after' => '/images/projects/project-13-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 13,
            ],
            [
                'title_fr' => 'Nettoyage de facade - Maison avec bow-window',
                'title_nl' => 'Gevelreiniging - Woning met erker',
                'description_fr' => 'Nettoyage et rejointoiement d\'une facade en brique avec bow-window arrondi.',
                'description_nl' => 'Reiniging en hervoegen van een bakstenen gevel met ronde erker.',
                'image_before' => '/images/projects/project-14-before.jpg',
                'image_after' => '/images/projects/project-14-after.jpg',
                'is_featured' => false,
                'is_published' => true,
                'order' => 14,
            ],
            [
                'title_fr' => 'Hydrogommage - Maison arriere',
                'title_nl' => 'Hydrogommage - Achtergevel',
                'description_fr' => 'Nettoyage par hydrogommage et rejointoiement de la facade arriere d\'une maison avec terrasse.',
                'description_nl' => 'Reiniging door hydrogommage en hervoegen van de achtergevel van een woning met terras.',
                'image_before' => '/images/projects/project-15-before.jpg',
                'image_after' => '/images/projects/project-15-after.jpg',
                'is_featured' => false,
                'is_published' => true,
                'order' => 15,
            ],
            [
                'title_fr' => 'Rejointoiement - Petite maison',
                'title_nl' => 'Hervoegen - Klein huis',
                'description_fr' => 'Rejointoiement complet d\'une petite maison en brique avec arches decoratives.',
                'description_nl' => 'Volledig hervoegen van een klein bakstenen huis met decoratieve bogen.',
                'image_before' => '/images/projects/project-16-before.jpg',
                'image_after' => '/images/projects/project-16-after.jpg',
                'is_featured' => false,
                'is_published' => true,
                'order' => 16,
            ],
            [
                'title_fr' => 'Nettoyage de facade - Immeuble de bureaux',
                'title_nl' => 'Gevelreiniging - Kantoorgebouw',
                'description_fr' => 'Nettoyage complet d\'un immeuble de bureaux avec facade en brique et grandes fenetres.',
                'description_nl' => 'Volledige reiniging van een kantoorgebouw met bakstenen gevel en grote ramen.',
                'image_before' => '/images/projects/project-17-before.jpg',
                'image_after' => '/images/projects/project-17-after.jpg',
                'is_featured' => false,
                'is_published' => true,
                'order' => 17,
            ],
            [
                'title_fr' => 'Peinture de facade - Maison bourgeoise',
                'title_nl' => 'Gevelschilderwerk - Burgerlijk huis',
                'description_fr' => 'Renovation et peinture complete d\'une facade de maison bourgeoise avec ornements.',
                'description_nl' => 'Renovatie en volledige schildering van een gevel van een burgerlijk huis met ornamenten.',
                'image_before' => '/images/projects/project-18-before.jpg',
                'image_after' => '/images/projects/project-18-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 18,
            ],
            [
                'title_fr' => 'Nettoyage et peinture - Maison avec bow-window',
                'title_nl' => 'Reiniging en schilderwerk - Woning met erker',
                'description_fr' => 'Nettoyage et peinture d\'une facade en brique avec bow-window et balcon en fer forge.',
                'description_nl' => 'Reiniging en schilderwerk van een bakstenen gevel met erker en smeedijzeren balkon.',
                'image_before' => '/images/projects/project-19-before.jpg',
                'image_after' => '/images/projects/project-19-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 19,
            ],
            [
                'title_fr' => 'Coating Murfill - Facade arriere',
                'title_nl' => 'Murfill Coating - Achtergevel',
                'description_fr' => 'Application de coating Murfill Waterproofing sur une facade arriere degradee avec fissures et decollement.',
                'description_nl' => 'Toepassing van Murfill Waterproofing coating op een beschadigde achtergevel met scheuren en loslating.',
                'image_before' => '/images/projects/project-20-before.jpg',
                'image_after' => '/images/projects/project-20-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 20,
            ],
            [
                'title_fr' => 'Rejointoiement - Maison mitoyenne brique',
                'title_nl' => 'Hervoegen - Bakstenen rijwoning',
                'description_fr' => 'Rejointoiement et nettoyage d\'une facade de maison mitoyenne en brique avec garage.',
                'description_nl' => 'Hervoegen en reiniging van een bakstenen rijwoninggevel met garage.',
                'image_before' => '/images/projects/project-21-before.jpg',
                'image_after' => '/images/projects/project-21-after.jpg',
                'is_featured' => false,
                'is_published' => true,
                'order' => 21,
            ],
            [
                'title_fr' => 'Peinture de facade - Immeuble avec balcon',
                'title_nl' => 'Gevelschilderwerk - Gebouw met balkon',
                'description_fr' => 'Renovation complete avec peinture d\'une facade d\'immeuble avec balcon en fer forge.',
                'description_nl' => 'Volledige renovatie met schildering van een gebouwgevel met smeedijzeren balkon.',
                'image_before' => '/images/projects/project-22-before.jpg',
                'image_after' => '/images/projects/project-22-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 22,
            ],
            [
                'title_fr' => 'Nettoyage de facade - Maison d\'angle',
                'title_nl' => 'Gevelreiniging - Hoekwoning',
                'description_fr' => 'Nettoyage et rejointoiement d\'une maison d\'angle en brique avec elements decoratifs.',
                'description_nl' => 'Reiniging en hervoegen van een bakstenen hoekwoning met decoratieve elementen.',
                'image_before' => '/images/projects/project-23-before.jpg',
                'image_after' => '/images/projects/project-23-after.jpg',
                'is_featured' => true,
                'is_published' => true,
                'order' => 23,
            ],
            [
                'title_fr' => 'Nettoyage de facade - Maison en pierre bleue',
                'title_nl' => 'Gevelreiniging - Woning in blauwe steen',
                'description_fr' => 'Nettoyage par hydrogommage d\'une facade en pierre bleue avec balcon et ornements.',
                'description_nl' => 'Reiniging door hydrogommage van een gevel in blauwe steen met balkon en ornamenten.',
                'image_before' => '/images/projects/project-24-before.jpg',
                'image_after' => '/images/projects/project-24-after.jpg',
                'is_featured' => false,
                'is_published' => true,
                'order' => 24,
            ],
        ];

        foreach ($projects as $projectData) {
            Project::create($projectData);
        }

        $this->command->info('Projects seeded successfully! Total: ' . count($projects));
    }
}
